language: python

cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.5
      env: TOXENV=py35-dj21
    - python: 3.5
      env: TOXENV=py35-dj22
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.6
      env: TOXENV=py36-dj21
    - python: 3.6
      env: TOXENV=py36-dj22
    - python: 3.6
      env: TOXENV=py36-dj30
    - python: 3.6
      env: TOXENV=py36-djdev
    - python: 3.7
      env: TOXENV=py37-dj21
    - python: 3.7
      env: TOXENV=py37-dj22
    - python: 3.7
      env: TOXENV=py37-dj30
    - python: 3.7
      env: TOXENV=py37-djdev
    - python: 3.8
      env: TOXENV=py38-dj21
    - python: 3.8
      env: TOXENV=py38-dj22
    - python: 3.8
      env: TOXENV=py38-dj30
    - python: 3.8
      env: TOXENV=py38-djdev
  allow_failures:
    - env: TOXENV=py35-djdev
    - env: TOXENV=py36-djdev
    - env: TOXENV=py37-djdev
    - env: TOXENV=py38-djdev
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
