[tox]
envlist =
    py38-dj{40,41,42,dev}
    py39-dj{40,41,42,dev}
    py310-dj{40,41,42,dev}
    py311-dj{41,42,dev}
    py312-dj{42,dev}

[testenv]
basepython =
    py38: python3.8
    py39: python3.9
    py310: python3.10
    py311: python3.11
    py312: python3.12
deps =
    dj40: Django>=4.0,<4.1
    dj41: Django>=4.1,<4.2
    dj42: Django>=4.2,<4.3
    djdev: https://github.com/django/django/archive/master.tar.gz
commands =
  python -V
  python -Wall test_proj/manage.py test

[pep8]
exclude = migrations,.tox,docs,test_proj,setup.py
